// constants/permissions.js
export const PERMISSIONS = {
  // Define - Product Management
  PRODUCTS_VIEW: 'products_view',
  PRODUCTS_EDIT: 'products_edit',
  CUSTOMERS_VIEW: 'customers_view',
  CUSTOMERS_EDIT: 'customers_edit',
  SUPPLIERS_VIEW: 'suppliers_view',
  SUPPLIERS_EDIT: 'suppliers_edit',
  CHART_OF_PRODUCTS_VIEW: 'chart_of_products_view',
  
  // Vouchers
  CASH_SALE: 'cash_sale',
  CASH_RECEIPTS: 'cash_receipts',
  CASH_PAYMENT: 'cash_payment',
  BANK_PAYMENT: 'bank_payment',
  MANUAL_SALE: 'manual_sale',
  MANUAL_PURCHASE: 'manual_purchase',
  SALE_RETURN: 'sale_return',
  PURCHASE_RETURN: 'purchase_return',
  QUOTATION: 'quotation',
  PURCHASE_ORDER: 'purchase_order',
  RAW_SALE: 'raw_sale',
  RAW_PURCHASE: 'raw_purchase',
  DAMAGE_IN: 'damage_in',
  DAMAGE_OUT: 'damage_out',
  PURCHASE: 'purchase',
  EXCHANGE: 'exchange',
  EXPENSES: 'expenses',
  PRODUCT_HISTORY: 'product_history',
  
  // Customers
  DEBIT_CUSTOMERS_VIEW: 'debit_customers_view',
  CREDIT_CUSTOMERS_VIEW: 'credit_customers_view',
  ACCOUNTS_RECEIVABLE_VIEW: 'accounts_receivable_view',
  ACCOUNTS_PAYABLE_VIEW: 'accounts_payable_view',
  
  // Reports
  PURCHASE_ORDER_LIST: 'purchase_order_list',
  PURCHASE_LIST: 'purchase_list',
  PURCHASE_WITHOUT_VALUES: 'purchase_without_values',
  PURCHASE_RETURN_LIST: 'purchase_return_list',
  PURCHASE_REPORT: 'purchase_report',
  QUOTATION_LIST: 'quotation_list',
  SALE_HISTORY: 'sale_history',
  SALE_PARTY_WISE: 'sale_party_wise',
  TOP_SALES: 'top_sales',
  SALES_RETURN: 'sales_return',
  SALE_RETURN_WITHOUT_VALUES: 'sale_return_without_values',
  EXCHANGE_LIST: 'exchange_list',
  PROFIT_REPORT: 'profit_report',
  RAW_PURCHASE_LIST: 'raw_purchase_list',
  RAW_SALE_LIST: 'raw_sale_list',
  COUNTER_SUMMARY: 'counter_summary',
  STOCK_REPORT: 'stock_report',
  CASH_RECEIPT_REPORT: 'cash_receipt_report',
  CASH_PAYMENT_REPORT: 'cash_payment_report',
  BANK_DEPOSITS: 'bank_deposits',
  BANK_PAYMENTS: 'bank_payments',
  JOURNAL_VOUCHER_LIST: 'journal_voucher_list',
  EXPENSES_LIST: 'expenses_list',
  ACCOUNTS_PAYABLE_RECEIVABLE: 'accounts_payable_receivable',
  GENERAL_LEDGER: 'general_ledger',
  
  // Final Accounts
  TRIAL_BALANCE: 'trial_balance',
  BALANCE_SHEET: 'balance_sheet',
  PROFIT_LOSS: 'profit_loss',
  CASH_BOOK: 'cash_book',
  RECEIVABLES: 'receivables',
  PAYABLES: 'payables',
  
  // Tools
  COMPANY_INFO: 'company_info',
  BACKUP: 'backup',
  SETTINGS: 'settings',
  PREFERENCES: 'preferences',
  USER_MANAGEMENT: 'user_management',
  
  // Help
  ABOUT: 'about',
  SUPPORT: 'support',
};

// Group permissions by category for easier management
export const PERMISSION_GROUPS = [
  {
    name: 'Define',
    permissions: [
      PERMISSIONS.PRODUCTS_VIEW,
      PERMISSIONS.CUSTOMERS_VIEW,
      PERMISSIONS.SUPPLIERS_VIEW,
      PERMISSIONS.CHART_OF_PRODUCTS_VIEW,
    ],
  },
  {
    name: 'Vouchers',
    permissions: [
      PERMISSIONS.CASH_SALE,
      PERMISSIONS.CASH_RECEIPTS,
      PERMISSIONS.CASH_PAYMENT,
      PERMISSIONS.BANK_PAYMENT,
      PERMISSIONS.MANUAL_SALE,
      PERMISSIONS.MANUAL_PURCHASE,
      PERMISSIONS.SALE_RETURN,
      PERMISSIONS.PURCHASE_RETURN,
      PERMISSIONS.QUOTATION,
      PERMISSIONS.PURCHASE_ORDER,
      PERMISSIONS.RAW_SALE,
      PERMISSIONS.RAW_PURCHASE,
      PERMISSIONS.DAMAGE_IN,
      PERMISSIONS.DAMAGE_OUT,
      PERMISSIONS.PURCHASE,
      PERMISSIONS.EXCHANGE,
      PERMISSIONS.EXPENSES,
      PERMISSIONS.PRODUCT_HISTORY,
    ],
  },
  {
    name: 'Customers',
    permissions: [
      PERMISSIONS.DEBIT_CUSTOMERS_VIEW,
      PERMISSIONS.CREDIT_CUSTOMERS_VIEW,
      PERMISSIONS.ACCOUNTS_RECEIVABLE_VIEW,
      PERMISSIONS.ACCOUNTS_PAYABLE_VIEW,
    ],
  },
  {
    name: 'Reports',
    permissions: [
      PERMISSIONS.PURCHASE_ORDER_LIST,
      PERMISSIONS.PURCHASE_LIST,
      PERMISSIONS.PURCHASE_WITHOUT_VALUES,
      PERMISSIONS.PURCHASE_RETURN_LIST,
      PERMISSIONS.PURCHASE_REPORT,
      PERMISSIONS.QUOTATION_LIST,
      PERMISSIONS.SALE_HISTORY,
      PERMISSIONS.SALE_PARTY_WISE,
      PERMISSIONS.TOP_SALES,
      PERMISSIONS.SALES_RETURN,
      PERMISSIONS.SALE_RETURN_WITHOUT_VALUES,
      PERMISSIONS.EXCHANGE_LIST,
      PERMISSIONS.PROFIT_REPORT,
      PERMISSIONS.RAW_PURCHASE_LIST,
      PERMISSIONS.RAW_SALE_LIST,
      PERMISSIONS.COUNTER_SUMMARY,
      PERMISSIONS.STOCK_REPORT,
      PERMISSIONS.CASH_RECEIPT_REPORT,
      PERMISSIONS.CASH_PAYMENT_REPORT,
      PERMISSIONS.BANK_DEPOSITS,
      PERMISSIONS.BANK_PAYMENTS,
      PERMISSIONS.JOURNAL_VOUCHER_LIST,
      PERMISSIONS.EXPENSES_LIST,
      PERMISSIONS.ACCOUNTS_PAYABLE_RECEIVABLE,
      PERMISSIONS.GENERAL_LEDGER,
    ],
  },
  {
    name: 'Final Accounts',
    permissions: [
      PERMISSIONS.TRIAL_BALANCE,
      PERMISSIONS.BALANCE_SHEET,
      PERMISSIONS.PROFIT_LOSS,
      PERMISSIONS.CASH_BOOK,
      PERMISSIONS.RECEIVABLES,
      PERMISSIONS.PAYABLES,
    ],
  },
  {
    name: 'Tools',
    permissions: [
      PERMISSIONS.COMPANY_INFO,
      PERMISSIONS.BACKUP,
      PERMISSIONS.SETTINGS,
      PERMISSIONS.PREFERENCES,
      PERMISSIONS.USER_MANAGEMENT,
    ],
  },
  {
    name: 'Help',
    permissions: [
      PERMISSIONS.ABOUT,
      PERMISSIONS.SUPPORT,
    ],
  },
];