const MENU_CONFIG = [
  {
    label: "Define",
    items: [
      { label: "Products", route: "/products" },
      { label: "Customers", route: "/customers" },
      { label: "Suppliers", route: "/suppliers" },
      { label: "Chart of Products", route: "/chart-of-products" },
    ],
  },
  {
    label: "Vouchers",
    items: [
      { label: "Cash Sale", route: "/sale", shortcut: "F3" },
      { label: "───" },
      { label: "Manual Sale Bill", route: "/manual-sale" },
      { label: "Manual Purchase Bill", route: "/manual-purchase" },
      { label: "───" },
      { label: "Sale Return", route: "/sale-return" },
      { label: "Purchase Return", route: "/purchase-return" },
      { label: "Quotation", route: "/quotation-page", shortcut: "Ctrl+Q" },
      { label: "Purchase Order", route: "/purchase-order" },
   
      { label: "───" },
      { label: "Raw Sale", route: "/raw-sale" },
      { label: "Damage In", route: "/damage-in" },
      { label: "Damage Out", route: "/damage-out" },
      { label: "Raw Purchase", route: "/raw-purchase" },
      { label: "Purchase", route: "/purchase" },
      { label: "───" },
      { label: "Exchange", route: "/exchange" },
      { label: "Expenses", route: "/expenses" },
    ],
  },
  {
    label: "Customers",
    items: [
      { label: "Debit Customers", route: "/debit-customers" },
      { label: "Credit Customers", route: "/credit-customers" },
   
      { label: "All Customers", route: "/customers" },
      { label: "───" },
      { label: "Accounts Receivable", route: "/accounts-receivable" },
      { label: "Accounts Payable", route: "/accounts-payable" },
    ],
  },
  {
    label: "Reports",
    items: [
      { label: "Chart of Products", route: "/chart-of-products" },
         { label: "Cash Receipts", route: "/cash-receipts" },
      { label: "Cash Payment", route: "/cash-payment" },
      { label: "───" },
      { label: "P.O", route: "/purchase-order-list" },
      { label: "Purchase", route: "/purchase-list" },
      { label: "Purchase w/o Values", route: "/purchase-without-values" },
      { label: "Purchase Return", route: "/purchase-return-list" },
         { label: "Purchase Report", route: "/purchase-report" },
      { label: "───" },
      { label: "Quotation", route: "/quotation-list" },
      { label: "───" },
      { label: "Sale", route: "/sale-history" },
      { label: "Sale Party wise", route: "/sale-party-wise" },
      { label: "Top Sales", route: "/top-sales" },
      { label: "Sales Return", route: "/sales-return" },
      { label: "Sale Return w/o Values", route: "/sale-return-without-values" },
      { label: "───" },
      { label: "Exchange", route: "/exchange-list" },
      { label: "───" },
      { label: "Profit Report Number wise", route: "/profit-report-number-wise" },
      { label: "Raw Purchase", route: "/raw-purchase-list" },
      { label: "Raw Sale", route: "/raw-sale-list" },
      { label: "───" },
      { label: "Counter Summary", route: "/counter-summary" },
      { label: "Stock", route: "/stock-report" },
      { label: "───" },
      { label: "Cash Receipt", route: "/cash-receipts-report" },
      { label: "Cash Payment", route: "/cash-payment-report" },
      { label: "Bank Deposits", route: "/bank-deposits" },
      { label: "Bank Payments", route: "/bank-payments" },
      { label: "───" },
      { label: "Journal Voucher", route: "/journal-voucher-list" },
      { label: "Expenses", route: "/expenses-list" },
      { label: "───" },
      { label: "Accounts Payable / Receivable", route: "/accounts-payable-receivable" },
      { label: "General Ledger", route: "/general-ledger" },
    ],
  },
  {
    label: "Final Accounts",
    items: [
      { label: "General Ledger", route: "/general-ledger" },
      { label: "Trial Balance", route: "/trial-balance" },
      { label: "Balance Sheet", route: "/balance-sheet" },
      { label: "Profit & Loss", route: "/profit-loss" },
      { label: "───" },
      { label: "Cash Book", route: "/cash-book" },
      { label: "Receivables", route: "/receivables" },
      { label: "Payables", route: "/payables" },
    ],
  },
  {
    label: "Tools",
    items: [
      { label: "Company Information", route: "/company-info" },
      { label: "Backup Data", route: "/backup" },
      { label: "───" },
      { label: "Settings", route: "/settings" },
      { label: "Preferences", route: "/preferences" },
    ],
  },
  {
    label: "Help",
    items: [
      { label: "About Software", route: "/about" },
      { label: "Contact Support", route: "/support" },
    ],
  },
];

export default MENU_CONFIG;